server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 50
    accept-count: 20000

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    suffix: .html
    prefix: templates/
    check-template: true
    check-template-location: true
    cache: false
  application:
    name: m3kong.com
  # database
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:6868/m3kong_blog
    username: m3kong_admin
    password: M3Kong@2025#6868
    pool:
      enabled: true
      initial-size: 50
      max-size: 200
      max-idle-time: 30m
  # database
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      indent-output: true
  # Redis server connection settings
  data:
    redis:
      host: 127.0.0.1 #auth-redis
      port: 7979
      password: ""
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5
      connect-timeout: 30000
  threads:
    virtual:
      enabled: true