server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 50
    accept-count: 20000

# redisson
redisson:
  address: "redis://127.0.0.1:7979"
  connectionPoolSize: 64

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    suffix: .html
    prefix: templates/
    check-template: true
    check-template-location: true
    cache: false
  application:
    name: m3kong.com
  # Local cache - caffeine
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10m
  # database
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:6868/m3kong_blog
    username: m3kong_admin
    password: M3Kong@2025#6868
    pool:
      enabled: true
      initial-size: 50
      max-size: 200
      max-idle-time: 30m
  # flyway migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    user: m3kong_admin
    password: M3Kong@2025#6868
    url: jdbc:postgresql://127.0.0.1:6868/m3kong_blog
  jackson:
    serialization:
      indent-output: true
  # Redis server connection settings
  data:
    redis:
      host: 127.0.0.1 #auth-redis
      port: 7979
      password: ""
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5
      connect-timeout: 30000
  threads:
    virtual:
      enabled: true